/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eKFRUYyRS72BUMSZdZJPiJ
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariants_0HgiicnFcM } from "../flink_3_d/PlasmicGlobalVariant__Screen"; // plasmic-import: 0-hgiicnFc-M/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariants_0HgiicnFcM
});
