/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eKFRUYyRS72BUMSZdZJPiJ
// Component: ZJ1sMuxC9zQ7
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  hasVariant
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Section from "../../Section"; // plasmic-import: 85lNmHdM8uqr/component
import PriceCard from "../../PriceCard"; // plasmic-import: 4LXP_MHVzitw/component
import { _useGlobalVariants } from "../flink3d/plasmic"; // plasmic-import: eKFRUYyRS72BUMSZdZJPiJ/projectModule
import { _useStyleTokens } from "../flink3d/PlasmicStyleTokensProvider"; // plasmic-import: eKFRUYyRS72BUMSZdZJPiJ/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "../flink3d/plasmic.module.css"; // plasmic-import: eKFRUYyRS72BUMSZdZJPiJ/projectcss
import sty from "./PlasmicPortfolio.module.css"; // plasmic-import: ZJ1sMuxC9zQ7/css

createPlasmicElementProxy;

export const PlasmicPortfolio__VariantProps = new Array();

export const PlasmicPortfolio__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPortfolio__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = _useGlobalVariants();
  const styleTokensClassNames = _useStyleTokens();
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicPortfolio.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicPortfolio.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicPortfolio.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"portfolio"}
          data-plasmic-override={overrides.portfolio}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.portfolio
          )}
        >
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__xUHnx)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: "/plasmic/flink_3_d/images/diagramImgSvg.svg",
              fullWidth: 300,
              fullHeight: 100,
              aspectRatio: 2.987552
            }}
          />

          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__qfNmN)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"774px"}
            loading={"lazy"}
            src={{
              src: "/plasmic/flink_3_d/images/ellipseLeftPng.png",
              fullWidth: 469,
              fullHeight: 742,
              aspectRatio: undefined
            }}
          />

          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__gSnpN)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: "/plasmic/flink_3_d/images/ellipseRightPng.png",
              fullWidth: 437,
              fullHeight: 742,
              aspectRatio: undefined
            }}
          />

          <Section
            data-plasmic-name={"diagramSection"}
            data-plasmic-override={overrides.diagramSection}
            children={null}
            className={classNames("__wab_instance", sty.diagramSection)}
            size={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "mobile"
                : undefined
            }
          />

          <Section
            data-plasmic-name={"gallerySection"}
            data-plasmic-override={overrides.gallerySection}
            children={null}
            className={classNames("__wab_instance", sty.gallerySection)}
            size={"fullContentGallery"}
          />

          <Section
            data-plasmic-name={"home"}
            data-plasmic-override={overrides.home}
            children={null}
            className={classNames("__wab_instance", sty.home)}
            size={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "mobile"
                : undefined
            }
          />

          <Section
            data-plasmic-name={"pricingSection"}
            data-plasmic-override={overrides.pricingSection}
            className={classNames("__wab_instance", sty.pricingSection)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__b7BxZ)}>
              <div
                data-plasmic-name={"columns"}
                data-plasmic-override={overrides.columns}
                className={classNames(projectcss.all, sty.columns)}
              >
                <div className={classNames(projectcss.all, sty.column__rUjSd)}>
                  <PriceCard
                    borders={["flatLeft"]}
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__ffzd5
                    )}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__eatGi)}>
                  <PriceCard
                    borders={["flatCenter"]}
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__ar7Sr
                    )}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__g0CPo)}
                  >
                    <div
                      data-plasmic-name={"text"}
                      data-plasmic-override={overrides.text}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "We Recommended"
                        : "We Recommended"}
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__bosi4)}>
                  <PriceCard
                    borders={["flatRight"]}
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__zeUb2
                    )}
                  />
                </div>
              </div>
            </div>
          </Section>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  portfolio: [
    "portfolio",
    "diagramSection",
    "gallerySection",
    "home",
    "pricingSection",
    "columns",
    "text"
  ],

  diagramSection: ["diagramSection"],
  gallerySection: ["gallerySection"],
  home: ["home"],
  pricingSection: ["pricingSection", "columns", "text"],
  columns: ["columns", "text"],
  text: ["text"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPortfolio__ArgProps,
          internalVariantPropNames: PlasmicPortfolio__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPortfolio__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "portfolio") {
    func.displayName = "PlasmicPortfolio";
  } else {
    func.displayName = `PlasmicPortfolio.${nodeName}`;
  }
  return func;
}

export const PlasmicPortfolio = Object.assign(
  // Top-level PlasmicPortfolio renders the root element
  makeNodeComponent("portfolio"),
  {
    // Helper components rendering sub-elements
    diagramSection: makeNodeComponent("diagramSection"),
    gallerySection: makeNodeComponent("gallerySection"),
    home: makeNodeComponent("home"),
    pricingSection: makeNodeComponent("pricingSection"),
    columns: makeNodeComponent("columns"),
    text: makeNodeComponent("text"),
    // Metadata about props expected for PlasmicPortfolio
    internalVariantProps: PlasmicPortfolio__VariantProps,
    internalArgProps: PlasmicPortfolio__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Portfolio",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicPortfolio;
/* prettier-ignore-end */
